### ISSUE TITLE
Support multiple cloning protocols

### ISSUE THREAD

**Issue by TheHipbot** [TheHipbot/hermes#6]
Hermes assumes that the clone url is using `https` protocol, but should have support for `ssh` and probably even `http`. This protocol should be in the config and set at the remote level. Possibly something like this:

```yaml
remotes: 
  github.com:
    protocol: ssh
```
